version: '3.8'
services:
  php-apache-environment:
    container_name: php-session-db
    image: andres42/php5.2-apache2.2:latest
    volumes:
      - ./php/src:/usr/local/apache2/htdocs
    ports:
      - 8013:80
  db:
      container_name: db-php-session
      image: mysql:5.5
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
          MYSQL_DATABASE: MYSQL_DATABASE
          MYSQL_USER: MYSQL_USER
          MYSQL_PASSWORD: MYSQL_PASSWORD
      ports:
          - "9911:3306"
  phpmyadmin:
    container_name: phpmyadmin-session-php
    image: phpmyadmin/phpmyadmin
    ports:
        - '8087:80'
    restart: always
    environment:
        PMA_HOST: db-php-session